AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Security Event Notification Stack with EventBridge, SQS, and Lambda'

Metadata:

  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Deployment Configuration"
        Parameters:
          - LambdaCodeBucket
          - LambdaCodeKey
      - Label:
          default: "Required Configuration"
        Parameters:
          - SlackWebhookUrl
          - AccountName
      - Label:
          default: "Optional Filtering"
        Parameters:
          - WhitelistResources
          - CriticalEvents
      - Label:
          default: "Optional Services (Enable as needed)"
        Parameters:
          - EnableGuardDuty
          - EnableSecurityHub
          - EnableIAM
          - EnableCloudTrail
          - EnableS3
          - EnableEC2
          - EnableConfig
          - EnableECS
          - EnableEKS
      - Label:
          default: "Advanced Settings"
        Parameters:
          - NotificationRetentionDays
          - LambdaTimeout
          - LambdaMemorySize
    ParameterLabels:
      LambdaCodeBucket:
        default: "S3 Bucket for Lambda Code"
      LambdaCodeKey:
        default: "S3 Key for Lambda Package"
      SlackWebhookUrl:
        default: "Slack Webhook URL"
      AccountName:
        default: "AWS Account Name"
      WhitelistResources:
        default: "Whitelisted Resource ARNs"
      CriticalEvents:
        default: "Critical Event Names"
      EnableGuardDuty:
        default: "Enable GuardDuty Monitoring"
      EnableSecurityHub:
        default: "Enable Security Hub Monitoring"
      EnableIAM:
        default: "Enable IAM Security Monitoring"
      EnableCloudTrail:
        default: "Enable CloudTrail Security Monitoring"
      EnableS3:
        default: "Enable S3 Security Monitoring"
      EnableEC2:
        default: "Enable EC2 Security Monitoring"
      EnableConfig:
        default: "Enable AWS Config Monitoring"
      EnableECS:
        default: "Enable ECS Monitoring"
      EnableEKS:
        default: "Enable EKS Monitoring"
      EnableEKS:
        default: "Enable EKS Monitoring"
      NotificationRetentionDays:
        default: "Log Retention (Days)"
      LambdaTimeout:
        default: "Lambda Timeout (Seconds)"
      LambdaMemorySize:
        default: "Lambda Memory (MB)"

Parameters:
  LambdaCodeBucket:
    Type: String
    Description: S3 bucket containing Lambda code

  LambdaCodeKey:
    Type: String
    Description: S3 key for Lambda code
    Default: 'function.zip'

  SlackWebhookUrl:
    Type: String
    Description: Slack Webhook URL for notifications
    NoEcho: true

  AccountName:
    Type: String
    Description: Name of the AWS account for notification identification
    Default: 'Unknown Account'

  WhitelistResources:
    Type: String
    Description: Comma-separated list of ARNs to whitelist from notifications
    Default: ''

  CriticalEvents:
    Type: String
    Description: Comma-separated list of critical event names
    Default: 'CreateUser,DeleteUser,CreateRole,DeleteRole,DeleteBucket'

  NotificationRetentionDays:
    Type: Number
    Description: Number of days to retain notifications in CloudWatch Logs
    Default: 30
    MinValue: 1
    MaxValue: 365

  LambdaTimeout:
    Type: Number
    Description: Lambda function timeout in seconds
    Default: 60
    MinValue: 1
    MaxValue: 900

  LambdaMemorySize:
    Type: Number
    Description: Lambda function memory size in MB
    Default: 256
    MinValue: 128
    MaxValue: 10240

  EnableGuardDuty:
    Type: String
    Description: Enable GuardDuty integration (true/false)
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'

  EnableSecurityHub:
    Type: String
    Description: Enable Security Hub integration (true/false)
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'

  EnableIAM:
    Type: String
    Description: Enable IAM security monitoring (true/false)
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'

  EnableCloudTrail:
    Type: String
    Description: Enable CloudTrail security monitoring (true/false)
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'

  EnableS3:
    Type: String
    Description: Enable S3 security monitoring (true/false)
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'

  EnableEC2:
    Type: String
    Description: Enable EC2 security monitoring (true/false)
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'

  EnableConfig:
    Type: String
    Description: Enable AWS Config integration (true/false)
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'

  EnableECS:
    Type: String
    Description: Enable ECS security monitoring (true/false)
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'

  EnableEKS:
    Type: String
    Description: Enable EKS security monitoring (true/false)
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'


Resources:
  NotificationLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: NotificationLambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !GetAtt NotificationQueue.Arn
              - Effect: Allow
                Action:
                  - ec2:DescribeSecurityGroups
                  - ec2:DescribeInstances
                  - ec2:DescribeVolumes
                  - s3:ListAllMyBuckets
                  - s3:GetBucketPublicAccessBlock
                  - s3:GetBucketEncryption
                  - s3:GetBucketVersioning
                  - s3:GetBucketLogging
                  - s3:GetBucketPolicy
                  - s3:GetBucketLocation
                  - cloudtrail:LookupEvents
                  - cloudtrail:DescribeTrails
                  - cloudtrail:GetTrailStatus
                  - iam:ListUsers
                  - iam:ListMFADevices
                  - iam:GetLoginProfile
                  - iam:ListPolicies
                  - iam:GetPolicyVersion
                  - iam:ListAccessKeys
                Resource: '*'
              - Effect: Allow
                Action:
                  - guardduty:GetFindings
                  - guardduty:ListDetectors
                  - guardduty:ListFindings
                Resource: '*'
              - Effect: Allow
                Action:
                  - securityhub:GetFindings
                  - securityhub:BatchImportFindings
                Resource: '*'
              - Effect: Allow
                Action:
                  - config:GetComplianceDetailsByConfigRule
                  - config:DescribeConfigRules
                  - config:DescribeConfigurationRecorders
                  - config:DescribeConfigurationRecorderStatus
                  - config:DescribeDeliveryChannels
                  - config:DescribeComplianceByConfigRule
                Resource: '*'
              - Effect: Allow
                Action:
                  - ecs:ListClusters
                  - ecs:DescribeClusters
                  - ecs:ListTaskDefinitions
                  - ecs:DescribeTaskDefinition
                  - ecs:ListServices
                  - ecs:DescribeServices
                Resource: '*'
              - Effect: Allow
                Action:
                  - eks:ListClusters
                  - eks:DescribeCluster
                  - eks:ListNodegroups
                  - eks:DescribeNodegroup
                Resource: '*'
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                Resource: '*'
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

  NotificationQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${AWS::StackName}-notification-queue
      VisibilityTimeout: !Ref LambdaTimeout
      MessageRetentionPeriod: 1209600  # 14 days
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt NotificationDLQ.Arn
        maxReceiveCount: 3

  NotificationDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${AWS::StackName}-notification-dlq
      VisibilityTimeout: !Ref LambdaTimeout
      MessageRetentionPeriod: 1209600  # 14 days
      RedrivePolicy:
        maxReceiveCount: 1

  NotificationLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-notification-lambda
      Runtime: python3.11
      Handler: security_notifier.handler.lambda_handler
      Role: !GetAtt NotificationLambdaRole.Arn
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Ref LambdaCodeKey
      Timeout: !Ref LambdaTimeout
      MemorySize: !Ref LambdaMemorySize
      Environment:
        Variables:
          SLACK_WEBHOOK_URL: !Ref SlackWebhookUrl
          ACCOUNT_NAME: !Ref AccountName
          WHITELIST_RESOURCES: !Ref WhitelistResources
          CRITICAL_EVENTS: !Ref CriticalEvents
          ENABLE_GUARDDUTY: !Ref EnableGuardDuty
          ENABLE_SECURITYHUB: !Ref EnableSecurityHub
          ENABLE_IAM: !Ref EnableIAM
          ENABLE_CLOUDTRAIL: !Ref EnableCloudTrail
          ENABLE_S3: !Ref EnableS3
          ENABLE_EC2: !Ref EnableEC2
          ENABLE_CONFIG: !Ref EnableConfig
          ENABLE_ECS: !Ref EnableECS
          ENABLE_EKS: !Ref EnableEKS
          LOG_LEVEL: INFO
          MAX_RETRIES: '3'
          RETRY_DELAY_SECONDS: '2'
          RATE_LIMIT_PER_MINUTE: '30'
          MAX_SLACK_MESSAGE_LENGTH: '3000'
      ReservedConcurrentExecutions: 5
      DeadLetterConfig:
        TargetArn: !GetAtt NotificationDLQ.Arn
      Tags:
        - Key: Application
          Value: SecurityNotification
        - Key: Environment
          Value: !Ref AccountName

  NotificationQueueTrigger:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt NotificationQueue.Arn
      FunctionName: !Ref NotificationLambda
      BatchSize: 10
      Enabled: true

  SecurityEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub ${AWS::StackName}-security-events
      Description: Rule to capture security-related events
      EventPattern:
        source:
          - aws.iam
          - aws.s3
          - aws.ec2
          - aws.cloudtrail
          - aws.config
          - aws.guardduty
          - aws.securityhub
          - aws.kms
          - aws.secretsmanager
          - aws.rds
          - aws.dynamodb
          - aws.redshift
          - aws.elasticache
          - aws.es
          - aws.workspaces
          - aws.organizations
          - aws.ecs
          - aws.eks
        detail-type:
          - AWS API Call via CloudTrail
          - AWS Console Sign In via CloudTrail
          - AWS Service Event
        detail:
          eventName:
            - CreateUser
            - DeleteUser
            - CreateRole
            - DeleteRole
            - AttachRolePolicy
            - DetachRolePolicy
            - PutBucketPolicy
            - DeleteBucketPolicy
            - AuthorizeSecurityGroupIngress
            - AuthorizeSecurityGroupEgress
            - RevokeSecurityGroupIngress
            - RevokeSecurityGroupEgress
            - CreateSecurityGroup
            - DeleteSecurityGroup
            - StartLogging
            - StopLogging
            - UpdateTrail
            - DeleteTrail
            - StartConfigurationRecorder
            - StopConfigurationRecorder
            - CreateConfigRule
            - DeleteConfigRule
            - CreateSecret
            - DeleteSecret
            - CreateKey
            - DeleteKey
            - CreateDBInstance
            - DeleteDBInstance
            - CreateTable
            - DeleteTable
            - CreateCluster
            - DeleteCluster
            - CreateCacheCluster
            - DeleteCacheCluster
            - CreateDomain
            - DeleteDomain
            - CreateWorkspace
            - DeleteWorkspace
            - CreateAccount
            - DeleteAccount
            - CreateCluster
            - DeleteCluster
            - UpdateCluster
            - CreateService
            - DeleteService
            - UpdateService
            - RegisterTaskDefinition
            - DeregisterTaskDefinition
            - UpdateTaskDefinition
            - CreateTaskSet
            - DeleteTaskSet
            - UpdateTaskSet
            - CreateNodegroup
            - DeleteNodegroup
            - UpdateNodegroup
            - CreateFargateProfile
            - DeleteFargateProfile
            - UpdateFargateProfile
      State: ENABLED
      Targets:
        - Arn: !GetAtt NotificationQueue.Arn
          Id: NotificationQueueTarget

Outputs:
  NotificationQueueUrl:
    Description: URL of the notification queue
    Value: !Ref NotificationQueue
  NotificationQueueArn:
    Description: ARN of the notification queue
    Value: !GetAtt NotificationQueue.Arn
  NotificationLambdaArn:
    Description: ARN of the notification Lambda function
    Value: !GetAtt NotificationLambda.Arn 